spring:
  datasource:
    url: ${APP_DB_URL:jdbc:postgresql://localhost:5432/orm_hibernate_demo}
    username: ${APP_DB_USERNAME:postgres}
    password: ${APP_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: false
